### ISSUE TITLE
run femnist error

### ISSUE THREAD

**Issue by Ronaldo-Stan** [zhenqincn/Snowball#1]
Hello Dear author:
       I run this code error:python.exe main.py -a myapp_ddif_ext --nodes 3597 -k 100 --model_save none --dataset femnist --malicious_ratio 0.2 --seed 69 --model mnistcnn --rounds 200 --gpu 0 --backdoor_target 61 --vt 0.5 --vae_initial 360 --vae_tuning 40 --v_step 0.05.
      And I do not found myapp_ddif_ext in your '--anti_poison'  argument in main.py
      How I resolve this error.Thank you.

**Comment by zhenqincn** [comment]
Hello, this is a typo. I think to run our approach, you should run main.py with "-a snowball". "myapp_ddif_ext" was just an option during our test. We forgot to rename it.
